//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloWin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FloWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Config {
            get {
                return ResourceManager.GetString("Command_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   障害物を描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_DrawWall {
            get {
                return ResourceManager.GetString("Command_DrawWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Exit {
            get {
                return ResourceManager.GetString("Command_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Pause {
            get {
                return ResourceManager.GetString("Command_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注ぐ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Pour {
            get {
                return ResourceManager.GetString("Command_Pour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Command_Resume {
            get {
                return ResourceManager.GetString("Command_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   液体描画をする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigStr_DrawLiquid {
            get {
                return ResourceManager.GetString("ConfigStr_DrawLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一般 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigStr_General {
            get {
                return ResourceManager.GetString("ConfigStr_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ショートカットキー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigStr_Header_Keys {
            get {
                return ResourceManager.GetString("ConfigStr_Header_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigStr_Header_Operation {
            get {
                return ResourceManager.GetString("ConfigStr_Header_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigStr_Keys {
            get {
                return ResourceManager.GetString("ConfigStr_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描画 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfigStr_Render {
            get {
                return ResourceManager.GetString("ConfigStr_Render", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon Ico_App {
            get {
                object obj = ResourceManager.GetObject("Ico_App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pour_source {
            get {
                object obj = ResourceManager.GetObject("pour_source", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   FloWin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Str_AppName {
            get {
                return ResourceManager.GetString("Str_AppName", resourceCulture);
            }
        }
    }
}
